services:
  gateway:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: <desired-address>
    environment:
      GATEWAY_SYSTEM_NAME: <desired-address>
      GATEWAY_PUBLIC_HTTP_PORT: 80
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: <desired-address>.localtest.me
    networks:
      - default
      - proxy

  database:
    healthcheck:
      disable: true
    labels:
      traefik.enable: "true"
      traefik.hostname: mssql
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
